version: "2"
services:
  socket:
    build: ./socket
    container_name: socket
    ports:
      - 4000:4000

  client:
    build: ./frontend
    container_name: client
    ports:
      - 3000:3000
    depends_on:
      - socket

  admin:
    build: ./admin
    container_name: admin
    ports:
      - 5000:5000

  nginx:
    depends_on:
      - client
      - admin
    restart: always
    build: ./nginx
    ports:
      - "80:80"
