version: "2"
services:
  socket:
    build: ./socket
    container_name: socket
    ports:
      - 4000:4000

  api:
    build: ./backend
    container_name: api
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
    ports:
      - 7500:7500
    environment:
      - NODE_ENV=development

  client:
    build: ./frontend
    container_name: client
    ports:
      - 3000:3000
    depends_on:
      - api
      - socket

  admin:
    build: ./admin
    container_name: admin
    ports:
      - 5000:5000
    depends_on:
      - api
